numpy == 1.26.4
pandas == 2.2.2
Python == 3.10.13 
torch == 2.1.2+cpu
transformers == 4.39.3
torchvision == 0.16.2+cpu
Pillow == 9.5.0
scikit-learn == 1.2.2
joblib == 1.4.0
Seaborn == 0.12.2
Matplotlib == 3.7.5